### ISSUE TITLE
KeyError: Caught KeyError in DataLoader worker process 2

### ISSUE THREAD

**Issue by ning-2022** [mxhulab/cryosieve#7] opened 2023-08-23 09:09 UTC
Hi experts,

  Thanks for giving this nice method to push resolution limits for cryo-EM map. I had successfully to go through the tutorial test. 
 It's really amazing. But, when I use cryosieve to run my own dataset, it complained some errors like that:

[ITER 0][Overall Retaining ratio: 100.00%][Threshold frequency : 40.00A]
[Subprocesses completed successfully in 977.63s.][RECONSTRUCT_DONE, ITERATION 0]
[Subprocesses completed successfully in 17.97s.][POSTPROCESS_DONE, ITERATION 0]
Traceback (most recent call last):
  File "/home/someoneelse/anaconda3/envs/CRYOSIEVE_ENV/bin/cryosieve-core", line 8, in <module>
    sys.exit(core())
  File "/home/someoneelse/anaconda3/envs/CRYOSIEVE_ENV/lib/python3.10/site-packages/cryosieve/core.py", line 82, in core
    main(args)
  File "/home/someoneelse/anaconda3/envs/CRYOSIEVE_ENV/lib/python3.10/site-packages/cryosieve/core.py", line 63, in main
    dataset_rem = sieve(dataset, volumes[i_subset], threshold, rem_number[i_subset], rank, world_size)
  File "/home/someoneelse/anaconda3/envs/CRYOSIEVE_ENV/lib/python3.10/site-packages/cryosieve/sieve.py", line 19, in sieve
    for i_batch, batch in enumerate(loader):
  File "/home/someoneelse/anaconda3/envs/CRYOSIEVE_ENV/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 530, in __next__
    data = self._next_data()
  File "/home/someoneelse/anaconda3/envs/CRYOSIEVE_ENV/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 1224, in _next_data
    return self._process_data(data)
  File "/home/someoneelse/anaconda3/envs/CRYOSIEVE_ENV/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 1250, in _process_data
    data.reraise()
  File "/home/someoneelse/anaconda3/envs/CRYOSIEVE_ENV/lib/python3.10/site-packages/torch/_utils.py", line 457, in reraise
    raise exception
KeyError: Caught KeyError in DataLoader worker process 2.
Original Traceback (most recent call last):
  File "/home/someoneelse/anaconda3/envs/CRYOSIEVE_ENV/lib/python3.10/site-packages/pandas/core/indexes/base.py", line 3653, in get_loc
    return self._engine.get_loc(casted_key)
  File "pandas/_libs/index.pyx", line 147, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 176, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 2606, in pandas._libs.hashtable.Int64HashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 2630, in pandas._libs.hashtable.Int64HashTable.get_item
KeyError: 0

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/someoneelse/anaconda3/envs/CRYOSIEVE_ENV/lib/python3.10/site-packages/torch/utils/data/_utils/worker.py", line 287, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/someoneelse/anaconda3/envs/CRYOSIEVE_ENV/lib/python3.10/site-packages/torch/utils/data/_utils/fetch.py", line 49, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/someoneelse/anaconda3/envs/CRYOSIEVE_ENV/lib/python3.10/site-packages/torch/utils/data/_utils/fetch.py", line 49, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/someoneelse/anaconda3/envs/CRYOSIEVE_ENV/lib/python3.10/site-packages/cryosieve/ParticleDataset.py", line 100, in __getitem__
    pixel_size  = row.loc[0, 'rlnImagePixelSize']
  File "/home/someoneelse/anaconda3/envs/CRYOSIEVE_ENV/lib/python3.10/site-packages/pandas/core/indexing.py", line 1096, in __getitem__
    return self.obj._get_value(*key, takeable=self._takeable)
  File "/home/someoneelse/anaconda3/envs/CRYOSIEVE_ENV/lib/python3.10/site-packages/pandas/core/frame.py", line 3877, in _get_value
    row = self.index.get_loc(index)
  File "/home/someoneelse/anaconda3/envs/CRYOSIEVE_ENV/lib/python3.10/site-packages/pandas/core/indexes/base.py", line 3655, in get_loc
    raise KeyError(key) from err
KeyError: 0

[Subprocesses reported an error. Return code: [1].][SIEVE_DONE, ITERATION 0] 

I run this command " cryosieve --reconstruct_software relion_reconstruct  --postprocess_software relion_postprocess --i run_data.star   --o cryosieve-output/  --mask mask.mrc  --angpix 1.04 --num_iters 10 --frequency_start 40 --frequency_end 3 --retention_ratio 0.8 --sym C1 "  in the main working directory of relion-4.0.0, which includes MotionCorr, Refine3D, PostProcess... fileholders.   And, the run_data.star is generated by 3D autoRefine program. The mask.mrc file is also produced based on Refine3D result.  Please help me. I have no idea for this error. Thanks again. 

Sincerely,
Ning

**Comment by Zarrathustra** [comment] 2023-08-23 09:22
If possible, would you please provide more detail about this issue of KeyError?

Thx

**Comment by Zarrathustra** [comment] 2023-08-23 09:25
Further, we strongly recommend you try demo cases, here in https://github.com/mxhulab/cryosieve-demos. Four datasets are deposited, along with expected result.

**Comment by Zarrathustra** [comment] 2023-08-23 09:38
OK. We think we have found the cause.

You are using a Relion 4 star file format, and there is a missing entry in your star file's data_optics part.

That is why
```
getitem
pixel_size = row.loc[0, 'rlnImagePixelSize']
File "/home/someoneelse/anaconda3/envs/CRYOSIEVE_ENV/lib/python3.10/site-packages/pandas/core/indexing.py", line 
```
occurred.

**Please manually add this entry (rlnImagePixelSize) in your STAR file, and then try again. It should fix the issue.**

In next release of CryoSieve, we will fix this issue.

**Comment by ning-2022** [comment] 2023-08-24 02:46
Hi Mingxu,

Thanks for your quick replies.  I had checked the header region of run_data.star file and noted that data_optics included rlnImagePixelSize item.  Maybe the Relion4.0 star file's format is quite different to the tutorial star file. This error may relate with other incomptiable entries.  Anyway, could you tell me about how do you generate this tutorial star file, by Relion or CryoSparc ?  Thus, I could reproduce my own star file like you done.  Thanks for your helps.  Here is the header of star file from my work. 

![data_optics](https://github.com/mxhulab/cryosieve/assets/107338944/31901b68-c6b1-4472-b908-b621f29b302c)

Sincerely,
Ning

**Comment by zerinf** [comment] 2023-08-24 06:43
Hi ning. If possible, would you please provide me the star file you used in this unsuccessful run? If the star file is too large, I believe first 100 rows should be sufficient.

**Comment by ning-2022** [comment] 2023-08-24 07:30
Okay, here it is, produced by Relion4.0.0    Thanks for your help.  Ning
[head100.txt](https://github.com/mxhulab/cryosieve/files/12426688/head100.txt)

**Comment by Zarrathustra** [comment] 2023-08-24 08:23
>  Anyway, could you tell me about how do you generate this tutorial star file, by Relion or CryoSparc ? Thus, I could reproduce my own star file like you done. Thanks for your helps. Here is the header of star file from my work.

Of course. The [script](https://github.com/asarnow/pyem/blob/master/csparc2star.py) from [pyem](https://github.com/asarnow/pyem) is used from conversion from .cs to .star.

We used the option "--relion2 --strip-uid". I believe that you might try to use "--relion2". It might solve your issue.

**Comment by zerinf** [comment] 2023-08-24 08:58
Thanks for your reply.

I just found a bug in our program when the input star file contains multiple optic groups. We will fix it in next version. Currently, you may use RELION 2 star format, or manually set all `rlnOpticsGroup` of particles to 1 (since three optic groups in your star file have the same parameters) to skip this bug.

**Comment by ning-2022** [comment] 2023-08-24 09:29
Thank zerinf and Mingxu that your suggestions really help me.  I will be very glad to hear about the next version release of CryoSieve.  Good luck！

**Comment by Zarrathustra** [comment] 2023-08-25 06:06
> Thank zerinf and Mingxu that your suggestions really help me. I will be very glad to hear about the next version release of CryoSieve. Good luck！

Thank you for your feedback of this bug. We have release version 1.2.1. and this bug has been fixed in this release.

Once again, thank you and this issue wil be closed.

**Closed as completed by Zarrathustra** 2023-08-25 06:06 UTC
